namespace JR.CodeGenerator.Models;

/// <summary>
/// DataBaseDto
/// </summary>
/// <autogeneratedoc />
public class DataBase
{
    /// <summary>
    /// Initializes a new instance of the <see cref="DataBase"/> class.
    /// </summary>
    /// <param name="id">The identifier.</param>
    /// <param name="name">The name.</param>
    /// <autogeneratedoc />
    public DataBase(int id, string name)
    {
        Id = id;
        Name = name;
    }
    /// <summary>
    /// Gets or sets the identifier.
    /// </summary>
    /// <value>
    /// The identifier.
    /// </value>
    /// <autogeneratedoc />
    public int Id { get; private set; }
    /// <summary>
    /// Gets or sets the name.
    /// </summary>
    /// <value>
    /// The name.
    /// </value>
    /// <autogeneratedoc />
    public string Name { get; private set; }
}
