namespace JR.CodeGenerator.Models;

/// <summary>
/// DataConnection
/// </summary>
/// <seealso cref="CommunityToolkit.Mvvm.ComponentModel.ObservableObject" />
/// <autogeneratedoc />
public class DataConnection
{
    /// <summary>
    /// Gets or sets the name of the server.
    /// </summary>
    /// <value>
    /// The name of the server.
    /// </value>
    /// <autogeneratedoc />
    public string ServerName { get; set; }
    /// <summary>
    /// Gets or sets the data base.
    /// </summary>
    /// <value>
    /// The data base.
    /// </value>
    /// <autogeneratedoc />
    public string DataBase { get; set; }
    /// <summary>
    /// Gets or sets a value indicating whether this instance is integrate security.
    /// </summary>
    /// <value>
    ///   <c>true</c> if this instance is integrate security; otherwise, <c>false</c>.
    /// </value>
    /// <autogeneratedoc />
    public bool IsIntegrateSecurity { get; set; }
    /// <summary>
    /// Gets or sets the name of the user.
    /// </summary>
    /// <value>
    /// The name of the user.
    /// </value>
    /// <autogeneratedoc />
    public string UserName { get; set; }
    /// <summary>
    /// Gets or sets the password.
    /// </summary>
    /// <value>
    /// The password.
    /// </value>
    /// <autogeneratedoc />
    public string Password { get; set; }
}

