using JR.CodeGenerator.Models;

namespace JR.CodeGenerator.Services;

/// <summary>
/// ISQL Server Service
/// </summary>
/// <autogeneratedoc />
public interface ISQLServerService
{
    /// <summary>
    /// Gets the data basese asynchronous.
    /// </summary>
    /// <param name="dataConnection">The data connection.</param>
    /// <returns></returns>
    /// <autogeneratedoc />
    Task<List<DataBase>> GetDataBaseseAsync(DataConnection dataConnection);
    /// <summary>
    /// Gets the datbles vistas.
    /// </summary>
    /// <param name="DataBaseName">Name of the data base.</param>
    /// <returns></returns>
    /// <autogeneratedoc />
    Task<List<TableView>> GetDatblesVistasAsync(DataConnection dataConnection);

    /// <summary>
    /// Generates the code.
    /// </summary>
    /// <param name="dataConnection">The data connection.</param>
    /// <param name="dataGeneral">The data general.</param>
    /// <returns></returns>
    /// <autogeneratedoc />
    Task GenerateCode(DataConnection dataConnection, DataGeneral dataGeneral);

    /// <summary>
    /// Generates the code base.
    /// </summary>
    /// <param name="general">The general.</param>
    /// <returns></returns>
    Task GenerateCodeBase(DataGeneral general);

    /// <summary>
    /// Sets the setting.
    /// </summary>
    /// <param name="setting">The setting.</param>
    /// <returns></returns>
    Task SetSetting(Setting setting);

    /// <summary>
    /// Gets the setting.
    /// </summary>
    /// <returns></returns>
    Task<Setting> GetSetting();

}

