using System.Windows;

namespace JR.CodeGenerator;

/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainViwsModwl : Window
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MainViwsModwl"/> class.
    /// </summary>
    /// <autogeneratedoc />
    public MainViwsModwl()
    {
        InitializeComponent();
    }
}